export const siteData = {
  name: 'Lyset',
  tagline: 'Algorithmic Trading Systems',
  description: 'Building high-performance trading bots for crypto markets, specialized in MEV capture, oracle lag exploitation, and quantitative strategies.',

  hero: {
    heading: 'lyset',
    subheading: 'Algorithmic Trading Systems',
  },

  projects: [
    {
      name: 'ETH RSI Scalper',
      description: 'High-frequency ETH scalping bot on Lighter DEX using RSI signals',
      details: 'Executes sub-second trades capturing micro volatility on Ethereum mainnet',
      status: 'LIVE',
      version: 'v21',
      performance: '$97.46 avg/month',
      winRate: '62%',
      sharpe: '1.8',
      maxDrawdown: '8%',
      github: 'https://github.com/0xde7c/lighter-bot',
      tags: ['Trading', 'Lighter DEX', 'RSI', 'Scalping'],
      featured: true,
      uptime: '6+ months',
    },
    {
      name: 'Polymarket Oracle Lag',
      description: 'Oracle lag arbitrage on Polymarket binary options',
      details: 'Exploits timing asymmetries in oracle updates for profitable binary trades',
      status: 'LIVE',
      version: 'v33',
      performance: '$68.37 baseline',
      winRate: '58%',
      sharpe: '1.6',
      maxDrawdown: '12%',
      github: 'https://github.com/0xde7c',
      tags: ['Prediction Markets', 'Oracle Lag', 'Polymarket'],
      featured: true,
      uptime: '3+ months',
    },
    {
      name: 'Solana Copy Trading',
      description: 'Real-time on-chain copy trading for Solana tokens',
      details: 'Detects whale transactions and automatically executes matched trades',
      status: 'LIVE',
      version: 'v2',
      performance: '0.24 SOL/day avg',
      winRate: '55%',
      sharpe: '1.4',
      maxDrawdown: '15%',
      github: 'https://github.com/0xde7c',
      tags: ['Solana', 'Copy Trading', 'Whale Detection'],
      featured: true,
      uptime: '4+ months',
    },
    {
      name: 'Multi-DEX Scanner',
      description: 'Cross-DEX arbitrage scanner with real-time pricing',
      details: 'Monitors Uniswap, Curve, Balancer for MEV opportunities',
      status: 'LIVE',
      version: 'v1',
      github: 'https://github.com/0xde7c',
      tags: ['Arbitrage', 'MEV', 'Multi-DEX'],
      featured: false,
    },
    {
      name: 'XAUUSD RSI Alerts',
      description: 'Forex RSI alert system for gold trading',
      details: 'Multi-timeframe RSI analysis with Telegram notifications',
      status: 'LIVE',
      github: 'https://github.com/0xde7c/gold-rsi-alerts',
      tags: ['Forex', 'Alerts', 'RSI'],
      featured: false,
    },
    {
      name: 'BTC/ETH/SOL RSI Alerts',
      description: 'Cross-asset RSI alert system',
      details: 'Real-time RSI signals across major cryptocurrencies',
      status: 'LIVE',
      github: 'https://github.com/0xde7c',
      tags: ['Crypto', 'Alerts', 'Multi-Asset'],
      featured: false,
    },
    {
      name: 'Solana MEV Bot',
      description: 'Sandwich detection and MEV extraction on Solana',
      details: 'Real-time MEV opportunities on high-velocity Solana pairs',
      status: 'BUILDING',
      version: 'v0.1',
      github: 'https://github.com/0xde7c',
      tags: ['Solana', 'MEV', 'Sandwich'],
      featured: true,
      uptime: 'In development',
    },
  ],

  stats: {
    totalBots: 6,
    liveDeployments: 6,
    marketsMonitored: [
      { name: 'Ethereum DEX', description: 'Low-latency scalping on Lighter DEX' },
      { name: 'Solana', description: 'On-chain detection: copy trading & MEV' },
      { name: 'Prediction Markets', description: 'Oracle lag arbitrage on Polymarket' },
      { name: 'Traditional Markets', description: 'Forex: XAUUSD RSI alerts' },
    ],
  },

  approach: {
    philosophy: 'Systematic trading across market inefficiencies: microstructure arbitrage, oracle lag, and on-chain signals. All strategies trade live capital with position limits and circuit breakers.',
    execution: 'Sub-100ms execution across distributed infrastructure',
    methodology: 'Real-time data processing, algorithmic signal generation, automated trade execution with risk controls',
  },

  contact: {
    email: 'adityadotb@gmail.com',
    github: 'https://github.com/0xde7c',
    twitter: 'https://x.com/0xde7c',
  },
}
